directories:
  output: release
  buildResources: build
appId: com.yourname.ocpomodoro
productName: OC Pomodoro
files:
  - filter:
      - dist/**/*
      - electron/**/*
win:
  target: portable
  icon: public/wonder.ico
electronVersion: 43.2.0
